version: '2'

services:
  world:
    build: ./Docker
    volumes:
      - ./Docker:/usr/src/app
    ports:
      - 12345:12345
      - 23456:23456

  db:
      image: mysql
      restart: always
      volumes:
      - ./initial_sql:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=123
      expose:
        - "3306"
      ports:
        - "8080:3306"

  web:
    build: ./web-app
    command: bash -c "sleep 10 && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web-app:/code
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - web

  ups:
      build: ./miniups
      command: bash -c "sleep 20 && ./proj0"
      volumes:
        - ./miniups:/code
      depends_on:
        - web
        - world
      expose:
        - "34567"
      ports:
        - "34567:34567"

volumes:
  data-volume: