// Code generated by protoc-gen-go.
// source: ups.proto
// DO NOT EDIT!

/*
Package UPS is a generated protocol buffer package.

It is generated from these files:
	ups.proto

It has these top-level messages:
	UConnect
	UConnected
	UGoPickup
	UFinished
	UDeliveryMade
	UDeliveryLocation
	UGoDeliver
	UCommands
	UResponses
*/
package UPS

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type UConnect struct {
	Reconnectid      *int64 `protobuf:"varint,1,opt,name=reconnectid" json:"reconnectid,omitempty"`
	Numtrucksinit    *int32 `protobuf:"varint,2,opt,name=numtrucksinit" json:"numtrucksinit,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UConnect) Reset()         { *m = UConnect{} }
func (m *UConnect) String() string { return proto.CompactTextString(m) }
func (*UConnect) ProtoMessage()    {}

func (m *UConnect) GetReconnectid() int64 {
	if m != nil && m.Reconnectid != nil {
		return *m.Reconnectid
	}
	return 0
}

func (m *UConnect) GetNumtrucksinit() int32 {
	if m != nil && m.Numtrucksinit != nil {
		return *m.Numtrucksinit
	}
	return 0
}

type UConnected struct {
	Worldid          *int64  `protobuf:"varint,1,req,name=worldid" json:"worldid,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UConnected) Reset()         { *m = UConnected{} }
func (m *UConnected) String() string { return proto.CompactTextString(m) }
func (*UConnected) ProtoMessage()    {}

func (m *UConnected) GetWorldid() int64 {
	if m != nil && m.Worldid != nil {
		return *m.Worldid
	}
	return 0
}

func (m *UConnected) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type UGoPickup struct {
	Truckid          *int32 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Whid             *int32 `protobuf:"varint,2,req,name=whid" json:"whid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UGoPickup) Reset()         { *m = UGoPickup{} }
func (m *UGoPickup) String() string { return proto.CompactTextString(m) }
func (*UGoPickup) ProtoMessage()    {}

func (m *UGoPickup) GetTruckid() int32 {
	if m != nil && m.Truckid != nil {
		return *m.Truckid
	}
	return 0
}

func (m *UGoPickup) GetWhid() int32 {
	if m != nil && m.Whid != nil {
		return *m.Whid
	}
	return 0
}

type UFinished struct {
	Truckid          *int32 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UFinished) Reset()         { *m = UFinished{} }
func (m *UFinished) String() string { return proto.CompactTextString(m) }
func (*UFinished) ProtoMessage()    {}

func (m *UFinished) GetTruckid() int32 {
	if m != nil && m.Truckid != nil {
		return *m.Truckid
	}
	return 0
}

func (m *UFinished) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *UFinished) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type UDeliveryMade struct {
	Truckid          *int32 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Packageid        *int64 `protobuf:"varint,2,req,name=packageid" json:"packageid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UDeliveryMade) Reset()         { *m = UDeliveryMade{} }
func (m *UDeliveryMade) String() string { return proto.CompactTextString(m) }
func (*UDeliveryMade) ProtoMessage()    {}

func (m *UDeliveryMade) GetTruckid() int32 {
	if m != nil && m.Truckid != nil {
		return *m.Truckid
	}
	return 0
}

func (m *UDeliveryMade) GetPackageid() int64 {
	if m != nil && m.Packageid != nil {
		return *m.Packageid
	}
	return 0
}

type UDeliveryLocation struct {
	Packageid        *int64 `protobuf:"varint,1,req,name=packageid" json:"packageid,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UDeliveryLocation) Reset()         { *m = UDeliveryLocation{} }
func (m *UDeliveryLocation) String() string { return proto.CompactTextString(m) }
func (*UDeliveryLocation) ProtoMessage()    {}

func (m *UDeliveryLocation) GetPackageid() int64 {
	if m != nil && m.Packageid != nil {
		return *m.Packageid
	}
	return 0
}

func (m *UDeliveryLocation) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *UDeliveryLocation) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type UGoDeliver struct {
	Truckid          *int32               `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Packages         []*UDeliveryLocation `protobuf:"bytes,2,rep,name=packages" json:"packages,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *UGoDeliver) Reset()         { *m = UGoDeliver{} }
func (m *UGoDeliver) String() string { return proto.CompactTextString(m) }
func (*UGoDeliver) ProtoMessage()    {}

func (m *UGoDeliver) GetTruckid() int32 {
	if m != nil && m.Truckid != nil {
		return *m.Truckid
	}
	return 0
}

func (m *UGoDeliver) GetPackages() []*UDeliveryLocation {
	if m != nil {
		return m.Packages
	}
	return nil
}

type UCommands struct {
	Deliveries       []*UGoDeliver `protobuf:"bytes,1,rep,name=deliveries" json:"deliveries,omitempty"`
	Pickups          []*UGoPickup  `protobuf:"bytes,2,rep,name=pickups" json:"pickups,omitempty"`
	Simspeed         *uint32       `protobuf:"varint,3,opt,name=simspeed" json:"simspeed,omitempty"`
	Disconnect       *bool         `protobuf:"varint,4,opt,name=disconnect" json:"disconnect,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *UCommands) Reset()         { *m = UCommands{} }
func (m *UCommands) String() string { return proto.CompactTextString(m) }
func (*UCommands) ProtoMessage()    {}

func (m *UCommands) GetDeliveries() []*UGoDeliver {
	if m != nil {
		return m.Deliveries
	}
	return nil
}

func (m *UCommands) GetPickups() []*UGoPickup {
	if m != nil {
		return m.Pickups
	}
	return nil
}

func (m *UCommands) GetSimspeed() uint32 {
	if m != nil && m.Simspeed != nil {
		return *m.Simspeed
	}
	return 0
}

func (m *UCommands) GetDisconnect() bool {
	if m != nil && m.Disconnect != nil {
		return *m.Disconnect
	}
	return false
}

type UResponses struct {
	Completions      []*UFinished     `protobuf:"bytes,1,rep,name=completions" json:"completions,omitempty"`
	Delivered        []*UDeliveryMade `protobuf:"bytes,2,rep,name=delivered" json:"delivered,omitempty"`
	Error            *string          `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Finished         *bool            `protobuf:"varint,4,opt,name=finished" json:"finished,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UResponses) Reset()         { *m = UResponses{} }
func (m *UResponses) String() string { return proto.CompactTextString(m) }
func (*UResponses) ProtoMessage()    {}

func (m *UResponses) GetCompletions() []*UFinished {
	if m != nil {
		return m.Completions
	}
	return nil
}

func (m *UResponses) GetDelivered() []*UDeliveryMade {
	if m != nil {
		return m.Delivered
	}
	return nil
}

func (m *UResponses) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *UResponses) GetFinished() bool {
	if m != nil && m.Finished != nil {
		return *m.Finished
	}
	return false
}

func init() {
}
