# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-04 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180131_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('view_questions', 'Can see questions and answers'), ('change_question_status', 'Can change the status of the question'))},
        ),
    ]
